{{- if .Values.persistence.gitlabData.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-data
  annotations:
  {{- if .Values.persistence.gitlabData.storageClass }}
    volume.beta.kubernetes.io/storage-class: "{{ if .Values.persistence.gitlabData.prefixReleaseToStorageClassName}}{{ .Release.Name }}-{{end}}{{ .Values.persistence.gitlabData.storageClass }}"
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.gitlabData.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.gitlabData.size | quote }}
{{- end }}
