{{- if .Values.registry.ingress.enabled }}
{{- if .Values.registry.ingress.tls }}
{{- if .Values.registry.ingress.tls.certificate }}
{{- if .Values.registry.ingress.tls.key }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: "{{ .Release.Name }}-registry-tls-secret"
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  tls.crt: "{{ .Values.registry.ingress.tls.certificate }}"
  tls.key: "{{ .Values.registry.ingress.tls.key }}"
{{- end }}
{{- end }}
{{- end }}
{{- end }}